{
 "title": "Player Data",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Volume",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (level) (\ncount_over_time({service_name=\"player-data/app\", level!=\"\"}[$__interval])\n)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Last Info Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{service_name=\"player-data/app\", level=\"info\"} | logfmt | line_format \"{{.level}} {{.msg}} method={{.method}} path={{.path}} status={{.status}} duration_ms={{.duration_ms}} ip={{.client_ip}}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per seconds",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (path, method) (rate(http_requests_total{service_name=\"player-data/app\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Total requests /player-data",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(player_data_requests_total{service_name=\"player-data/app\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Profiling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Samples",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "labelSelector": "{service_name=\"player-data/app\"}",
       "profileTypeId": "process_cpu:samples:count:cpu:nanoseconds"
      }
     ]
    },
    {
     "title": "CPU samples",
     "type": "flamegraph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "labelSelector": "{service_name=\"player-data/app\"}",
       "profileTypeId": "process_cpu:samples:count:cpu:nanoseconds"
      }
     ]
    },
    {
     "title": "Memory Alloc",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "labelSelector": "{service_name=\"player-data/app\"}",
       "profileTypeId": "memory:alloc_space:bytes:space:bytes"
      }
     ]
    },
    {
     "title": "Memory Alloc",
     "type": "flamegraph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "labelSelector": "{service_name=\"player-data/app\"}",
       "profileTypeId": "memory:alloc_space:bytes:space:bytes"
      }
     ]
    }
   ]
  }
 ]
}