apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - grafana-datasources-configmap.yaml
  - grafana.yaml
  - pyroscope-configmap.yaml
  - pyroscope.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: opusmajor
      app.kubernetes.io/component: observability
